# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci
# IP: The module: 'c_counter_binary_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci
# IP: The module: 'c_counter_binary_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
