# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/el3ctrician/PrimaProva/PrimaProva.cache/wt [current_project]
set_property parent.project_path /home/el3ctrician/PrimaProva/PrimaProva.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{/home/el3ctrician/PrimaProva/Modified COE/1stMemory.coe}}
add_files {{/home/el3ctrician/PrimaProva/Modified COE/2ndMemory.coe}}
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/xbip_multadd_0_synth_1/xbip_multadd_0.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/xbip_multadd_0_synth_1/xbip_multadd_0.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/mult_gen_0_synth_1/mult_gen_0.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/mult_gen_0_synth_1/mult_gen_0.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/xbip_multadd_1_synth_1/xbip_multadd_1.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/xbip_multadd_1_synth_1/xbip_multadd_1.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/input_memory_synth_1/input_memory.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/input_memory_synth_1/input_memory.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_1_synth_1/c_counter_binary_1.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_1_synth_1/c_counter_binary_1.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_2_synth_1/c_counter_binary_2.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/c_counter_binary_2_synth_1/c_counter_binary_2.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/inputMemory2_synth_1/inputMemory2.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/inputMemory2_synth_1/inputMemory2.dcp]
add_files -quiet /home/el3ctrician/PrimaProva/PrimaProva.runs/outputMemoryCore_synth_1/outputMemoryCore.dcp
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.runs/outputMemoryCore_synth_1/outputMemoryCore.dcp]
read_vhdl -library xil_defaultlib {
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/synchronizer.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/OMC2.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/OMC1.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/OutputMemory.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/OMCfull.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/IMC2.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/IMC.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/Converter.vhd
  /home/el3ctrician/PrimaProva/PrimaProva.srcs/sources_1/new/FullChip.vhd
}
read_xdc /home/el3ctrician/PrimaProva/PrimaProva.srcs/constrs_1/new/co.xdc
set_property used_in_implementation false [get_files /home/el3ctrician/PrimaProva/PrimaProva.srcs/constrs_1/new/co.xdc]

synth_design -top FullChip -part xc7a100tcsg324-2
write_checkpoint -noxdef FullChip.dcp
catch { report_utilization -file FullChip_utilization_synth.rpt -pb FullChip_utilization_synth.pb }
