webtalk_init -webtalk_dir /home/el3ctrician/PrimaProva/PrimaProva.sim/sim_2/behav/xsim.dir/ChipSimulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 28 04:18:32 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211179483_0_0_300" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "72386e6a-82a2-4a99-ace0-debcd7e7b17f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6e8a9aeaaaeb400da17febe9a0680db3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 8.5 (jessie)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1199.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "267044_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1924884287 -regid "211179483_0_0_300" -xml /home/el3ctrician/PrimaProva/PrimaProva.sim/sim_2/behav/xsim.dir/ChipSimulation_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/el3ctrician/PrimaProva/PrimaProva.sim/sim_2/behav/xsim.dir/ChipSimulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/el3ctrician/PrimaProva/PrimaProva.sim/sim_2/behav/xsim.dir/ChipSimulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
